title: Hícaro Dânrlley
email: hdanrlley1@gmail.com
description: >-
  Sou um desenvolvedor back-end que gosta de documentar minhas opiniões a respeito do mundo
  da Ciência da Computação e do desenvolvimento de software no geral.
baseurl: ""
url: ""
github_username:  HicaroD
linkedin_username: hicaromiguel

theme: minima
plugins:
  - jekyll-feed
